version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mmallahham/reverseproxy 
  backend_user:
    build:
      context: ../../restapi-user
    image: mmallahham/udagram-user
  backend_feed:
    build:
      context: ../../restapi-feed  
    image: mmallahham/udagram-feed
  frontend:
    build:
      context: ../../frontend  
    image: mmallahham/udagram-frontend
