apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: mmallahham/udagram-feed:latest
        name: backend-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"              
        env:
        - name: URL
          value: $URL
        - name: AWS_BUCKET
          value: $AWS_BUCKET
        - name: AWS_PROFILE
          value: $AWS_PROFILE
        - name: AWS_REGION
          value: $AWS_REGION
        - name: JWT_SECRET
          value: $JWT_SECRET
        - name: POSTGRES_DB
          value: $POSTGRES_DB
        - name: POSTGRES_HOST
          value: $POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          value: $POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          value: $POSTGRES_USERNAME    
        - name: AWS_SECRET_ACCESS_KEY
          value: $AWS_SECRET_ACCESS_KEY    
        - name: AWS_ACCESS_KEY_ID
          value: $AWS_ACCESS_KEY_ID
        - name: AWS_DEFAULT_REGION
          value: $AWS_DEFAULT_REGION    
      restartPolicy: Always                