apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: mmallahham/udagram-user
        name: backend-user 
        imagePullPolicy: Always
        ports:
          - containerPort: 80  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: URL
          value: $URL 
        - name: JWT_SECRET
          value: $JWT_SECRET
        - name: POSTGRES_DB
          value: $POSTGRES_DB
        - name: POSTGRES_HOST
          value: $POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          value: $POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          value: $POSTGRES_USERNAME
        - name: AWS_SECRET_ACCESS_KEY
          value: $AWS_SECRET_ACCESS_KEY    
        - name: AWS_ACCESS_KEY_ID
          value: $AWS_ACCESS_KEY_ID    
      restartPolicy: Always
      


