apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 80
  selector:
    service: reverseproxy
  type: LoadBalancer    
